Inventory Strategy lifo-fifo enumerations
devblogs-ir/InventoryStrategy pull request #12
Opened 2024-01-02 15:34 UTC by davobag

#Inventory Strategy lifo-fifo enumerations

2024-01-02 19:27 UTC, thisisnabi requested changes
Please solve these issues.

2024-01-02 19:27 UTC, thisisnabi commented on sources/DavoodBaghdadi/InventoryStrategy/InventoryWrapper.cs
> +            default: return new FIFOEnumerator(Products);
You must enter the cases specifically.

Change it into the 

```

case InventoryManagementApproach.LastInFirstOut:
default:
        return....

```

2024-01-02 19:27 UTC, thisisnabi commented on sources/DavoodBaghdadi/InventoryStrategy/Enumerators/FIFOEnumerator.cs
> +        else { return false; }
You can remove the else statement and just return `false`

2024-01-03 21:07 UTC, merged

2024-01-04 08:25 UTC, davobag commented
Thanks dear Nabi !
I resolved your comments in local repository, so I did not push according to merge and close the request.