Implemented Inventory Strategy
devblogs-ir/InventoryStrategy pull request #13
Opened 2024-01-02 16:12 UTC by lilmont

An inventory strategy which returns products wither in FIFO or LIFO manner.

2024-01-02 18:27 UTC, mohammadKarimi requested changes
your code was perfect, but I want you to be better than now. so I reject your code to improve it. 
your faults were not about functionality, all of them were about clean code, and principals.

2024-01-02 18:27 UTC, mohammadKarimi commented on sources/Niloo Mont/InventoryStrategy/Enumerators/FIFOEnumerator.cs
> +    public T Current
please follow 1 line break for each method.

2024-01-02 18:27 UTC, mohammadKarimi commented on sources/Niloo Mont/InventoryStrategy/Enumerators/FIFOEnumerator.cs
> +    public FIFOEnumerator(List<T> list)
please follow 1 line break for each method.

2024-01-02 18:27 UTC, mohammadKarimi commented on sources/Niloo Mont/InventoryStrategy/Enumerators/FIFOEnumerator.cs
> +public class FIFOEnumerator<T> : IEnumerator<T>
please write summary for you class.

2024-01-02 18:27 UTC, mohammadKarimi commented on sources/Niloo Mont/InventoryStrategy/InventoryWrapper.cs
> +    private InventoryManagementApproach _managementApproach;
this field must be readonly. if you fill it in your constructor.

2024-01-02 18:27 UTC, mohammadKarimi commented on sources/Niloo Mont/InventoryStrategy/InventoryWrapper.cs
> +        _list = new List<T>();
use collection Expression in c# 12.

2024-01-02 18:27 UTC, mohammadKarimi commented on sources/Niloo Mont/InventoryStrategy/InventoryWrapper.cs
> +            while (enumerator.MoveNext())
DRY

2024-01-02 18:27 UTC, mohammadKarimi commented on sources/Niloo Mont/InventoryStrategy/InventoryWrapper.cs
> +            while (enumerator.MoveNext())
DRY. please refactor it. 
you are writing the same code in different if.

2024-01-02 18:27 UTC, mohammadKarimi commented on sources/Niloo Mont/InventoryStrategy/Models/Enums/InventoryManagementApproach.cs
> +public enum InventoryManagementApproach
inherit of byte. (micro-optimization)
in this case, it is not important, but if you want to map this enum in your DB you should inherit from byte.

2024-01-02 18:27 UTC, mohammadKarimi commented on sources/Niloo Mont/InventoryStrategy/Models/Phone.cs
> +
remove use-less break line.

2024-01-02 18:27 UTC, mohammadKarimi commented on sources/Niloo Mont/InventoryStrategy/Models/Phone.cs
> +    public Phone(int code, string name) : base(code, name)
use primary constructor.

2024-01-02 18:27 UTC, mohammadKarimi commented on sources/Niloo Mont/InventoryStrategy/Models/Product.cs
> +    public Product(int code, string name)
Primary constructor.

2024-01-02 18:27 UTC, mohammadKarimi commented on sources/Niloo Mont/InventoryStrategy/Models/TV.cs
> +    public TV(int code, string name) : base(code, name)
again Primary constructor.

2024-01-03 08:08 UTC, lilmont commented on sources/Niloo Mont/InventoryStrategy/InventoryWrapper.cs
> +        _list = new List<T>();
I tried changing this line to _list = []; but the compiler doesn't recognize this pattern. How can I resolve it?

2024-01-03 08:16 UTC, lilmont commented on sources/Niloo Mont/InventoryStrategy/Models/Phone.cs
> +    public Phone(int code, string name) : base(code, name)
I have the same problem I had with collection Expression. I would appreciate if you could help me with that.

2024-01-03 17:40 UTC, mohammadKarimi approved these changes

2024-01-03 17:40 UTC, mohammadKarimi commented on sources/Niloo Mont/InventoryStrategy/Enumerators/FIFOEnumerator.cs
> +public class FIFOEnumerator<T> : IEnumerator<T>
for summary: please write /// it makes you a standard summary.

2024-01-03 17:40 UTC, mohammadKarimi commented on sources/Niloo Mont/InventoryStrategy/Enumerators/FIFOEnumerator.cs
> +    public bool MoveNext()
line break.

2024-01-03 17:40 UTC, mohammadKarimi commented on sources/Niloo Mont/InventoryStrategy/Enumerators/FIFOEnumerator.cs
> +        List<T> localList = _list;
why you are assigning to localList?

2024-01-03 17:40 UTC, mohammadKarimi commented on sources/Niloo Mont/InventoryStrategy/Enumerators/LIFOEnumerator.cs
> +    public void Reset()
line break.

2024-01-03 17:40 UTC, mohammadKarimi commented on sources/Niloo Mont/InventoryStrategy/InventoryWrapper.cs
> +        _list = new List<T>();
it is not important. it is ok, I am sending you some tips to use.

2024-01-03 17:40 UTC, mohammadKarimi commented on sources/Niloo Mont/InventoryStrategy/Models/Phone.cs
> +    public Phone(int code, string name) : base(code, name)
are you using .net 8 ?

2024-01-03 17:40 UTC, merged